version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://127.0.0.1:5000/v1
      - VITE_APP_NAME=Vistagram
      - VITE_CLOUDINARY_CLOUD_NAME=da8qkmwfc
      - VITE_CLOUDINARY_API_KEY=788816714345857
      - VITE_CLOUDINARY_API_SECRET=TDQjgvs-KNK1IT_1H9N5Eoiw4GU

    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: vistagram-db-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: ./backend
    command: alembic upgrade head
    environment:
      - backend/.env
    depends_on:
      - db

volumes:
  postgres_data:
