"""update db schema & fix shared post schema

Revision ID: 1a8dcc7e3c28
Revises: 9bcad4d5430d
Create Date: 2025-08-28 03:00:45.690997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8dcc7e3c28'
down_revision = '9bcad4d5430d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_url')

    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('viewed_by', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('shared_post_clicks_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['shared_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['viewed_by'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shared_post_clicks_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('viewed_by')
        batch_op.drop_column('shared_by')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
