"""Added relation shared post clicks

Revision ID: 6ed6251ea981
Revises: 281f6fb70e17
Create Date: 2025-08-11 18:46:05.233783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed6251ea981'
down_revision: Union[str, Sequence[str], None] = '281f6fb70e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_post_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_post_clicks_id'), 'shared_post_clicks', ['id'], unique=False)
    op.alter_column('posts', 'post_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'share_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('share_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'post_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_shared_post_clicks_id'), table_name='shared_post_clicks')
    op.drop_table('shared_post_clicks')
    # ### end Alembic commands ###
