"""model method changes

Revision ID: 955380c12d3d
Revises: 1a8dcc7e3c28
Create Date: 2025-08-28 12:55:41.061696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955380c12d3d'
down_revision = '1a8dcc7e3c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_likes_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_id'))

    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_post_clicks_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_post_clicks_id'), ['id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_likes_id'), ['id'], unique=False)

    # ### end Alembic commands ###
