"""added new remove foriegn keys

Revision ID: b215edc5dc90
Revises: 65ff57f8f582
Create Date: 2025-08-10 17:07:37.627810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b215edc5dc90'
down_revision: Union[str, Sequence[str], None] = '65ff57f8f582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('share_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'share_count')
    op.drop_column('posts', 'post_url')
    # ### end Alembic commands ###
