"""added column post_url not null constraint

Revision ID: b7d141fe4576
Revises: a393cb4a0307
Create Date: 2025-08-10 17:04:46.031826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d141fe4576'
down_revision: Union[str, Sequence[str], None] = 'a393cb4a0307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('share_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'share_count')
    op.drop_column('posts', 'post_url')
    # ### end Alembic commands ###
