"""add unique constraint on shared 

Revision ID: cf3db173f42c
Revises: 955380c12d3d
Create Date: 2025-08-28 18:23:35.442489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3db173f42c'
down_revision = '955380c12d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_shared_post_click', ['shared_by', 'post_id', 'viewed_by'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    with op.batch_alter_table('shared_post_clicks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_shared_post_click', type_='unique')

    # ### end Alembic commands ###
